### ISSUE TITLE
Update issues in TheHive project

### ISSUE THREAD

**Issue by aw350m33d** [oscd-initiative/oscd-task-management#4]
Update existing issues and rename them to the regular backlog format.

- [x] [OSCD Initiative] Develop Responder for Gmail ([issue 859](https://github.com/TheHive-Project/Cortex-Analyzers/issues/859); [PR 891](https://github.com/TheHive-Project/Cortex-Analyzers/pull/891))
- [x] [OSCD Initiative] Develop Responder for Azure Active Directory ([issue 858](https://github.com/TheHive-Project/Cortex-Analyzers/issues/858); [PR 906](https://github.com/TheHive-Project/Cortex-Analyzers/pull/906))
- [x] [OSCD Initiative] Develop Responder for Duo Security ([issue 857](https://github.com/TheHive-Project/Cortex-Analyzers/issues/857); [PR 964](https://github.com/TheHive-Project/Cortex-Analyzers/pull/964))
- [x] [OSCD Initiative] Develop Responder for CB Response / Carbon Black Endpoint Detection and Response ([issue 856](https://github.com/TheHive-Project/Cortex-Analyzers/issues/856))
- [x] [OSCD Initiative] Develop Responder for Palo Alto NGFW ([issue 855](https://github.com/TheHive-Project/Cortex-Analyzers/issues/855); [PR 886](https://github.com/TheHive-Project/Cortex-Analyzers/pull/886))

**Comment by nadouani** [comment]
Hello, 

All issues and available PRs have been accepted and will released with version 3.0.0.

Unfortunately [Issue 856](https://github.com/TheHive-Project/Cortex-Analyzers/issues/856) has not received any PR.
