### ISSUE TITLE
Update issues for ART tests in the Sigma project

### ISSUE THREAD

**Issue by aw350m33d** [oscd-initiative/oscd-task-management#7]
Update existing issues and rename them to the regular backlog format.
- [ ] [OSCD Initiative] Develop Sigma rules for Atomic Red Team test (Windows) ([issue 1013](https://github.com/SigmaHQ/sigma/issues/1013))
- [ ] [OSCD Initiative] Develop Sigma rules for Atomic Red Team test (macOS) ([issue 1012](https://github.com/SigmaHQ/sigma/issues/1012))
- [ ] [OSCD Initiative] Develop Sigma rules for Atomic Red Team test (Linux) ([issue 1011](https://github.com/SigmaHQ/sigma/issues/1011))
