### ISSUE TITLE
Update issues for hunting cases in the Sigma project

### ISSUE THREAD

**Issue by aw350m33d** [oscd-initiative/oscd-task-management#9]
Update existing issues and rename them to the regular backlog format.
- [ ] [OSCD Initiative] Develop Sigma rules for Lateral Movement in Windows Infrastructure ([issue 576](https://github.com/SigmaHQ/sigma/issues/576))
- [ ] [OSCD Initiative] Develop Sigma rules for PowerShell Abuse ([issue 575](https://github.com/SigmaHQ/sigma/issues/575))
- [ ] [OSCD Initiative] Develop Sigma rules for Privilege Escalation in Windows Environment ([issue 574](https://github.com/SigmaHQ/sigma/issues/574))
